# Generated by Django 5.1 on 2024-08-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to=None)),
            ],
        ),
    ]
