# Generated by Django 5.1 on 2024-08-14 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockwatchlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='amount',
            new_name='price',
        ),
    ]
