# Generated by Django 5.1 on 2024-10-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_watchlist',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=10),
        ),
    ]
