# Generated by Django 5.1 on 2024-10-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_rename_owner_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_value',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leaderboard',
            field=models.BooleanField(default=True),
        ),
    ]
