# Generated by Django 5.1 on 2024-10-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='stocks',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='stocks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
